### ISSUE TITLE
I'm a using apid version so i need to use different prompts

### ISSUE THREAD

**Issue by AsusuZ** [vincenthsu/systemd-ngrok#23]
I have to us this promt --remote-addr=<YOUR_ADDRESS> how should i configure to run this?

**Comment by Shad3ious** [comment]
I have the same issue. However, if you run just ngrok. It works. `ngrok tcp {IP:PORT} --remote-addr=<YOUR_ADDRESS>`

**Comment by Shad3ious** [comment]
I did find this article: https://ngrok.com/docs/tcp/?cty=agent-config
It shows that in a yml file you can do this:
```
tunnels:
  example:
    proto: tcp
    addr: 3389
    remote_addr: 1.tcp.eu.ngrok.io:12345
```
